<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table = 'categories';
        $now = Carbon::now()->format('Y-m-d H:i:s');
        $categories = [
            //['google_name'=>'','display_name'=>'','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'accounting','display_name'=>'accounting','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'airport','display_name'=>'airport','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'amusement_park','display_name'=>'amusement_park','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'aquarium','display_name'=>'aquarium','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'art_gallery','display_name'=>'art_gallery','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'atm','display_name'=>'atm','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'bakery','display_name'=>'bakery','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'bank','display_name'=>'bank','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'bar','display_name'=>'bar','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'beauty_salon','display_name'=>'beauty_salon','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'bicycle_store','display_name'=>'bicycle_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'book_store','display_name'=>'book_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'bowling_alley','display_name'=>'bowling_alley','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'bus_station','display_name'=>'bus_station','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'cafe','display_name'=>'cafe','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'campground','display_name'=>'campground','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'car_dealer','display_name'=>'car_dealer','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'car_rental','display_name'=>'car_rental','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'car_repair','display_name'=>'car_repair','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'car_wash','display_name'=>'car_wash','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'casino','display_name'=>'casino','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'cemetery','display_name'=>'cemetery','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'church','display_name'=>'church','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'city_hall','display_name'=>'city_hall','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'clothing_store','display_name'=>'clothing_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'convenience_store','display_name'=>'convenience_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'courthouse','display_name'=>'courthouse','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'dentist','display_name'=>'dentist','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'department_store','display_name'=>'department_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'doctor','display_name'=>'doctor','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'electrician','display_name'=>'electrician','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'electronics_store','display_name'=>'electronics_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'embassy','display_name'=>'embassy','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'fire_station','display_name'=>'fire_station','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'florist','display_name'=>'florist','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'funeral_home','display_name'=>'funeral_home','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'furniture_store','display_name'=>'furniture_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'gas_station','display_name'=>'gas_station','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'gym','display_name'=>'gym','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'hair_care','display_name'=>'hair_care','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'hardware_store','display_name'=>'hardware_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'hindu_temple','display_name'=>'hindu_temple','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'home_goods_store','display_name'=>'home_goods_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'hospital','display_name'=>'hospital','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'insurance_agency','display_name'=>'insurance_agency','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'jewelry_store','display_name'=>'jewelry_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'laundry','display_name'=>'laundry','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'lawyer','display_name'=>'lawyer','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'library','display_name'=>'library','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'liquor_store','display_name'=>'liquor_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'local_government_office','display_name'=>'local_government_office','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'locksmith','display_name'=>'locksmith','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'lodging','display_name'=>'lodging','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'meal_delivery','display_name'=>'meal_delivery','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'meal_takeaway','display_name'=>'meal_takeaway','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'mosque','display_name'=>'mosque','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'movie_rental','display_name'=>'movie_rental','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'movie_theater','display_name'=>'movie_theater','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'moving_company','display_name'=>'moving_company','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'museum','display_name'=>'museum','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'night_club','display_name'=>'night_club','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'painter','display_name'=>'painter','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'park','display_name'=>'park','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'parking','display_name'=>'parking','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'pet_store','display_name'=>'pet_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'pharmacy','display_name'=>'pharmacy','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'physiotherapist','display_name'=>'physiotherapist','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'plumber','display_name'=>'plumber','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'police','display_name'=>'police','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'post_office','display_name'=>'post_office','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'real_estate_agency','display_name'=>'real_estate_agency','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'restaurant','display_name'=>'restaurant','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'roofing_contractor','display_name'=>'roofing_contractor','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'rv_park','display_name'=>'rv_park','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'school','display_name'=>'school','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'shoe_store','display_name'=>'shoe_store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'shopping_mall','display_name'=>'shopping_mall','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'spa','display_name'=>'spa','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'stadium','display_name'=>'stadium','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'storage','display_name'=>'storage','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'store','display_name'=>'store','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'subway_station','display_name'=>'subway_station','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'synagogue','display_name'=>'synagogue','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'taxi_stand','display_name'=>'taxi_stand','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'train_station','display_name'=>'train_station','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'transit_station','display_name'=>'transit_station','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'travel_agency','display_name'=>'travel_agency','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'university','display_name'=>'university','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'veterinary_care','display_name'=>'veterinary_care','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'zoo','display_name'=>'zoo','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'administrative_area_level_1','display_name'=>'administrative_area_level_1','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'administrative_area_level_2','display_name'=>'administrative_area_level_2','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'administrative_area_level_3','display_name'=>'administrative_area_level_3','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'administrative_area_level_4','display_name'=>'administrative_area_level_4','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'administrative_area_level_5','display_name'=>'administrative_area_level_5','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'colloquial_area','display_name'=>'colloquial_area','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'country','display_name'=>'country','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'establishment','display_name'=>'establishment','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'finance','display_name'=>'finance','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'floor','display_name'=>'floor','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'food','display_name'=>'food','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'general_contractor','display_name'=>'general_contractor','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'geocode','display_name'=>'geocode','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'health','display_name'=>'health','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'intersection','display_name'=>'intersection','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'locality','display_name'=>'locality','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'natural_feature','display_name'=>'natural_feature','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'neighborhood','display_name'=>'neighborhood','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'place_of_worship','display_name'=>'place_of_worship','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'political','display_name'=>'political','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'point_of_interest','display_name'=>'point_of_interest','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'post_box','display_name'=>'post_box','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'postal_code','display_name'=>'postal_code','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'postal_code_prefix','display_name'=>'postal_code_prefix','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'postal_code_suffix','display_name'=>'postal_code_suffix','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'postal_town','display_name'=>'postal_town','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'premise','display_name'=>'premise','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'room','display_name'=>'room','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'route','display_name'=>'route','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'street_address','display_name'=>'street_address','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'street_number','display_name'=>'street_number','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'sublocality','display_name'=>'sublocality','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'sublocality_level_4','display_name'=>'sublocality_level_4','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'sublocality_level_5','display_name'=>'sublocality_level_5','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'sublocality_level_3','display_name'=>'sublocality_level_3','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'sublocality_level_2','display_name'=>'sublocality_level_2','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'sublocality_level_1','display_name'=>'sublocality_level_1','created_at'=> $now,'updated_at' => $now],
            ['google_name'=>'subpremise','display_name'=>'subpremise','created_at'=> $now,'updated_at' => $now],
        ];
        DB::table($table)->insert($categories);
    }
}
